terasolunaorg/tutorial-apps

todo-rest/scripts/convert-rest-xml.sh

---
#12 
410c482c1e9cd40398a2be14371532e642e6ac3e
---

remove authentication #12

---

first-spring-security/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

---
#1 
d5fff91e35c1c08213e199340bec898945fd5481
---

gather create script #1

---

first-spring-security/scripts/create-app.sh
first-spring-security/scripts/generate-security-project.sh
todo-rest/scripts/create-app.sh
todo-rest/scripts/generate-rest-project.sh
todo/scripts/create-app.sh
todo/scripts/generate-app-project.sh

---
#1 
262e09a75fe0e02c36ef6f64770168ad0948bc5a
3b182d33fcb50e81c168ea02c58ec2af8d1ab7fa
---

mkdir and move target-project #1

---

secure-login-demo/secure-login-selenium/src/test/java/org/terasoluna/securelogin/selenium/loginform/AccountLockTest.java
secure-login-demo/secure-login-selenium/src/test/java/org/terasoluna/securelogin/selenium/loginform/PasswordLeakageMeasuresTest.java
secure-login-demo/secure-login-selenium/src/test/java/org/terasoluna/securelogin/selenium/loginform/PasswordReissueTest.java
secure-login-demo/secure-login-selenium/src/test/java/org/terasoluna/securelogin/selenium/loginform/PasswordStrengthTest.java

modify test script in secure-login to get screen capture #18

add test script to get screen capture #18

---

README.md

Add decription on readme #6

---

session-tutorial-complete/session-tutorial-complete-web/src/main/java/com/example/session/app/account/AccountUpdateController.java

fix compilation error #23

---

.travis.yml
README.md

Please review #15.
Old working PR is #16.

Add travis script to validate generates and builds #15

---

secure-login-demo/scripts/secure-login-demo/secure-login-web/src/main/resources/META-INF/spring/spring-security.xml.sed
secure-login-demo/secure-login-web/src/main/webapp/WEB-INF/views/login/login.jsp

Reflect Spring Security failure-url improvement #26

---

todo-rest/scripts/generate-rest-project.sh
todo/scripts/generate-app-project.sh
todo/scripts/old-resources/5.2.x/src/main/java/jpa/todo/domain/model/Todo.java

correct mapping between field and column name.#40

---

secure-login-demo/secure-login-web/src/main/webapp/WEB-INF/views/common/error/fileUploadError.jsp
secure-login-demo/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCharacterError.jsp

modify html tag.#42

---

first-spring-security/scripts/generate-security-project.sh

add script of delete unnecessary test source.#41

---

first-spring-security/scripts/generate-project-from-maven-central.sh
first-spring-security/scripts/generate-project-from-nexus.sh
first-spring-security/scripts/generate-security-project.sh
secure-login-demo/scripts/generate-app-project.sh
secure-login-demo/scripts/generate-project-from-maven-central.sh
secure-login-demo/scripts/generate-project-from-nexus.sh
session-tutorial-complete/scripts/generate-project-from-maven-central.sh
session-tutorial-complete/scripts/generate-project-from-nexus.sh
session-tutorial-complete/scripts/generate-session-complete-project.sh
session-tutorial-init/scripts/generate-project-from-maven-central.sh
session-tutorial-init/scripts/generate-project-from-nexus.sh
session-tutorial-init/scripts/generate-session-init-project.sh
todo-rest/scripts/generate-project-from-maven-central.sh
todo-rest/scripts/generate-project-from-nexus.sh
todo-rest/scripts/generate-rest-project.sh
todo/scripts/generate-app-project.sh
todo/scripts/generate-project-from-maven-central.sh
todo/scripts/generate-project-from-nexus.sh

remove -DarchetypeCatalog option.#39

---

first-spring-security/scripts/generate-project-from-nexus.sh
secure-login-demo/scripts/generate-project-from-nexus.sh
secure-login-demo/scripts/old-resources/5.1.x/scripts/generate-app-project.sh
session-tutorial-complete/scripts/generate-project-from-nexus.sh
session-tutorial-init/scripts/generate-project-from-nexus.sh
todo-rest/scripts/generate-project-from-nexus.sh
todo/scripts/generate-project-from-nexus.sh

Fix to specify maven archetype plugin version.#49

---

ISSUE_TEMPLATE.md

add issue template #54

---

PULL_REQUEST_TEMPLATE.md

add PR template #55

---

.travis.yml
common/scripts/change-maven-settings.sh
common/scripts/generate-project.sh
docs/README.md

support snapshot version archetype. #63

---

.travis.yml
todo-rest/scripts/convert-rest-test.sh

Please review #57.
This is changes for version 5.3.x.

apply old resources for 5.3.x. #57

---

.travis.yml
common/scripts/change-maven-settings.sh
common/scripts/generate-project.sh
docs/README.md
todo-rest/scripts/convert-rest-test.sh
todo/src-jpa/main/java/todo/domain/model/Todo.java

Please review #57.
This is changes for version 5.2.x.

apply old resources for 5.2.x. #57

---

todo-rest/scripts/convert-rest-test.sh

fix comment. #57

---

common/scripts/change-maven-settings.sh
common/scripts/generate-project.sh

fix condition to decide maven archetype repository. #75

---

common/scripts/change-maven-settings.sh
common/scripts/generate-project.sh

Please review #75.
This PR is backport from https://github.com/terasolunaorg/tutorial-apps/pull/76.

[5.3.x]fix condition to decide maven archetype repository. #75

---

.travis.yml

add firefox version at .travis.yml #85

---

ISSUE_TEMPLATE.md

Add Final Solution section to Issue Template. #87

---

secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/unlock/unlockComplete.jsp

Fix the title #53

---

secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/unlock/unlockComplete.jsp

Please review #53. Backport for 5.3.1.

[5.3.1] Fix the title #53

---

secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/unlock/unlockComplete.jsp

[5.2.x]Fix the title #53

---

secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/unlock/unlockComplete.jsp

[5.1.x]Fix the title #53

---

.travis.yml

[5.0.x] change oraclejdk7 for oraclejdk8 in .travis.yml #111

---

.travis.yml

[1.0.x] change oraclejdk7 for oraclejdk8 in .travis.yml #111

---

.travis.yml

[5.3.x] update SNAPSHOT version to 5.3.2 #114

---

pom.xml

fix artifact version. #80

---

pom.xml

[5.3.x] fix artifact version. #80

---

pom.xml

[5.2.x] fix artifact version. #80

---

pom.xml

[5.1.x] fix artifact version. #80

---

pom.xml

[5.0.x] fix artifact version. #80

---

pom.xml

[1.0.x] fix artifact version. #80

---

common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

add firefox preference setting of no proxy. #132

---

session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

Please review #132 .
This PR is backport for 5.3.x

[5.3.x] fix test class #132

---

.travis.yml
pom.xml

update SNAPSHOT version. #136

---

.travis.yml
README.md
pom.xml

[5.4.x] update version #136

---

docs/README.md

add eclipse directory explanation #140

---

docs/README.md

[5.4.x] add eclipse directory explanation #140

---

docs/README.md

[5.3.x] add eclipse directory explanation #140

---

docs/README.md

[5.2.x] add eclipse directory explanation #140

---

docs/README.md

[5.1.x] add eclipse directory explanation #140

---

docs/README.md

[5.0.x] add eclipse directory explanation #140

---

docs/README.md

This PR is backport for 1.0.x .

[1.0.x] add eclipse directory explanation #140

---

.travis.yml
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

Travis CI Broken using Selenium #152 #154

---

secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
secure-login-demo/src/secure-login-env/src/main/resources/logback.xml

Please review #149 .
In addition to described at #149 , I modified indent at 39f5986 commit.

Reflect blank project change  #149

---

common/scripts/convert-common-css.sh
todo/src/main/webapp/WEB-INF/views/todo/list.jsp

reflect guideline change #172

---

.travis.yml
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

[5.4.x]Travis CI Broken using Selenium #152 #154

---

.travis.yml
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

[5.3.x]Travis CI Broken using Selenium #152 #154

---

first-spring-security/src/main/webapp/WEB-INF/views/account/view.jsp
first-spring-security/src/main/webapp/login.jsp

Please review #129 .
Coflict happened because files does not exist .
(cherry picked from commit 70ef190831ed9d3469bfdf870e9b0398f0ce13d5)
Conflicts:
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/fileUploadError.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCharacterError.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 9155324397316d5a6d5b1883432b31e893e9fe08)
Conflicts:
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/accountConfirm.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/accountCreateForm.jsp …

[5.0.x]reflect blank project change #129

---

first-spring-security/src/main/webapp/WEB-INF/views/account/view.jsp
first-spring-security/src/main/webapp/login.jsp

Please review #129 .
This PR is backport for 1.0.x .
Coflict happened because files does not exist .
(cherry picked from commit 70ef190831ed9d3469bfdf870e9b0398f0ce13d5)
Conflicts:
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/fileUploadError.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/invalidCharacterError.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 9155324397316d5a6d5b1883432b31e893e9fe08)
Conflicts:
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/accountConfirm.jsp
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/accountCreateForm.jsp …

[1.0.x]reflect blank project change #129

---

common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

Please review #132 .
(travis fail, but we can not fix travis by cherry-pick unless we merge this PR.)

[5.2.x]add firefox preference setting of no proxy. #132

---

common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

Please review #132 .
(travis fail, but we can not fix travis by cherry-pick unless we merge this PR.)

[5.1.x]add firefox preference setting of no proxy. #132

---

.travis.yml
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

[5.2.x] Travis CI Broken using Selenium #152 #154

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

This PR is sideport form terasolunaorg/guideline#3283 .

Change spring-mvc-rest.xml creation method from copy to create #194

---

.travis.yml
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

[5.1.x] Travis CI Broken using Selenium #152 #154

---

first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

modify loginForm.jsp indent 4 spaces #179

---

first-spring-security/scripts/convert-security-test.sh
first-spring-security/scripts/convert-security-xml.sh
first-spring-security/src/main/java/com/example/security/app/login/LoginController.java
first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[1.0.x] move login.jsp to webapp/WEB-INF/views #174

---

common/scripts/convert-common-css.sh
todo/src/main/webapp/WEB-INF/views/todo/list.jsp

(cherry picked from commit b30b32d7a1127fc2cf58ebf7f01bfa4a49333561)
Please review #172 .

[5.4.x] reflect guideline change #172

---

common/scripts/convert-common-css.sh
todo/src/main/webapp/WEB-INF/views/todo/list.jsp

(cherry picked from commit b30b32d7a1127fc2cf58ebf7f01bfa4a49333561)
Please review #172 .

[5.2.x] reflect guideline change #172

---

secure-login-demo/src/secure-login-web/src/main/java/com/example/securelogin/app/account/AccountController.java

fix does not work to the screen to complete creation of new account #213

---

secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/view.jsp

fix the request to the password change screen is set to POST #214

---

common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java

(cherry picked from commit d07ce31bd3d649d7a7e39c25204798c08faf745e)
Please review #183 .

[5.1.x] fix bug that web browser does not close at the end of the test #183

---

common/scripts/convert-common-css.sh
todo/src/main/webapp/WEB-INF/views/todo/list.jsp

(cherry picked from commit b30b32d7a1127fc2cf58ebf7f01bfa4a49333561)
Please review #172 .

[5.1.x] reflect guideline change #172

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

[5.4.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

[5.3.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

[5.2.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

[5.0.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

Conflict happened because sed command differrent from other version .
To apply this PR for 1.0.x version, I fixed this PR change at 1fe3c47642d71742192df540742b6a899a057b25 commit in addition to `cherry-pick` change .

[1.0.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

(cherry picked from commit b26d109db534f10bea2848a2d031b35a36f35584)
Please review #179

[5.4.x] modify jsp indent 4 spaces #179

---

first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

(cherry picked from commit b26d109db534f10bea2848a2d031b35a36f35584)
Please review #179

[5.3.x] modify jsp indent 4 spaces #179

---

first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

(cherry picked from commit b26d109db534f10bea2848a2d031b35a36f35584)
Please review #179

[5.2.x] modify jsp indent 4 spaces #179

---

first-spring-security/src/main/webapp/WEB-INF/views/login/loginForm.jsp

(cherry picked from commit b26d109db534f10bea2848a2d031b35a36f35584)
(cherry picked from commit 97c9bb44cbee624cab063dd073d929b26e4d8059)
Please review #179

[5.1.x] modify jsp indent 4 spaces #179

---

secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-codelist.xml
secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-infra.xml
secure-login-demo/src/secure-login-env/src/main/resources/logback.xml

[5.2.x] Reflect blank project change #149

---

session-tutorial-complete/scripts/convert-session-complete-java.sh
session-tutorial-complete/scripts/convert-session-complete-jsp.sh
session-tutorial-complete/scripts/convert-session-complete-properties.sh
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
session-tutorial-init/scripts/convert-session-init-jsp.sh
session-tutorial-init/scripts/convert-session-init-properties.sh
session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[5.5.x]Session Tutorial Application is not implemented for tiles #248

---

common/scripts/convert-common-test.sh
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/create-app.sh
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

Fix selenium version to 2.46.0 #139

---

todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/copy-sources.sh
todo-rest/src/main/resources/META-INF/spring/spring-mvc-rest.xml

[5.1.x] Change spring-mvc-rest.xml creation method from copy to create #194

---

common/scripts/convert-common-test.sh
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/create-app.sh
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

(cherry picked from commit c562caea9d1a0b6345ba0d28d265314f6386354c)
Please review #139 .

[5.4.x] Fix selenium version to 2.46.0 #139

---

common/scripts/convert-common-test.sh
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/create-app.sh
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.3.x] Fix selenium version to 2.46.0 #139

---

session-tutorial-complete/scripts/convert-session-complete-java.sh
session-tutorial-complete/scripts/convert-session-complete-jsp.sh
session-tutorial-complete/scripts/convert-session-complete-properties.sh
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
session-tutorial-init/scripts/convert-session-init-jsp.sh
session-tutorial-init/scripts/convert-session-init-properties.sh
session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[5.4.x]Session Tutorial Application is not implemented for tiles #248

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/convert-secure-login-jsp.sh
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/scripts/convert-secure-login-xml.sh
secure-login-demo/scripts/create-app.sh
secure-login-demo/src/secure-login-env/configs/context.xml
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

Since groupId can not be set freely, it changed to a fixed value.
Although artifactId can be freely set, it changed to prepare default values for usability improvement.

Change groupId to a fixed value. Change artifactId to provide default values. #215

---

.gitignore
first-spring-security/scripts/convert-security-jsp.sh
first-spring-security/scripts/convert-security-test.sh
first-spring-security/scripts/convert-security-xml.sh
first-spring-security/scripts/create-app.sh
todo-rest/scripts/convert-rest-java.sh
todo-rest/scripts/convert-rest-msg.sh
todo-rest/scripts/convert-rest-test.sh
todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/create-app.sh
todo/scripts/convert-todo-css.sh
todo/scripts/convert-todo-infra.sh
todo/scripts/convert-todo-test.sh
todo/scripts/create-app.sh

[5.0.x] Remove the target-project folder before mkdir target-project #181

---

.gitignore
first-spring-security/scripts/convert-security-jsp.sh
first-spring-security/scripts/convert-security-test.sh
first-spring-security/scripts/convert-security-xml.sh
first-spring-security/scripts/create-app.sh
todo-rest/scripts/convert-rest-java.sh
todo-rest/scripts/convert-rest-msg.sh
todo-rest/scripts/convert-rest-test.sh
todo-rest/scripts/convert-rest-xml.sh
todo-rest/scripts/create-app.sh
todo/scripts/convert-todo-infra.sh
todo/scripts/convert-todo-test.sh
todo/scripts/create-app.sh

Please review #181 .
This PR is backport for 1.0.x .

[1.0.x] Remove the target-project folder before mkdir target-project #181

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/convert-secure-login-jsp.sh
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/scripts/convert-secure-login-xml.sh
secure-login-demo/scripts/create-app.sh
secure-login-demo/src/secure-login-env/configs/context.xml
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.4.x] Change groupId to a fixed value. Change artifactId to provide default values. #215

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/convert-secure-login-jsp.sh
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/scripts/convert-secure-login-xml.sh
secure-login-demo/scripts/create-app.sh
secure-login-demo/src/secure-login-env/configs/context.xml
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.3.x] Change groupId to a fixed value. Change artifactId to provide default values. #215

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/convert-secure-login-jsp.sh
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/scripts/convert-secure-login-xml.sh
secure-login-demo/scripts/create-app.sh
secure-login-demo/src/secure-login-env/configs/context.xml
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.2.x] Change groupId to a fixed value. Change artifactId to provide default values. #215

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
secure-login-demo/scripts/convert-secure-login-jsp.sh
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/scripts/convert-secure-login-xml.sh
secure-login-demo/scripts/create-app.sh
secure-login-demo/src/secure-login-env/configs/context.xml
session-tutorial-complete/scripts/create-app.sh
session-tutorial-init/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.1.x] Change groupId to a fixed value. Change artifactId to provide default values. #215

---

.travis.yml
docs/README.md
first-spring-security/scripts/create-app.sh
todo-rest/scripts/create-app.sh
todo/scripts/create-app.sh

[5.0.x] Change groupId to a fixed value. Change artifactId to provide default values. #215

---

session-tutorial-complete/scripts/convert-session-complete-java.sh
session-tutorial-complete/scripts/convert-session-complete-jsp.sh
session-tutorial-complete/scripts/convert-session-complete-properties.sh
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
session-tutorial-init/scripts/convert-session-init-jsp.sh
session-tutorial-init/scripts/convert-session-init-properties.sh
session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[5.3.x]Session Tutorial Application is not implemented for tiles #248

---

session-tutorial-complete/scripts/convert-session-complete-java.sh
session-tutorial-complete/scripts/convert-session-complete-jsp.sh
session-tutorial-complete/scripts/convert-session-complete-properties.sh
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
session-tutorial-init/scripts/convert-session-init-jsp.sh
session-tutorial-init/scripts/convert-session-init-properties.sh
session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[5.2.x]Session Tutorial Application is not implemented for tiles #248

---

session-tutorial-complete/scripts/convert-session-complete-java.sh
session-tutorial-complete/scripts/convert-session-complete-jsp.sh
session-tutorial-complete/scripts/convert-session-complete-properties.sh
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateConfirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateFinish.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm1.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/account/updateForm2.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/cart/viewCart.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/confirm.jsp
session-tutorial-complete/src/session-tutorial-complete-web/src/main/webapp/WEB-INF/views/order/finish.jsp
session-tutorial-init/scripts/convert-session-init-jsp.sh
session-tutorial-init/scripts/convert-session-init-properties.sh
session-tutorial-init/src/session-tutorial-init-web/src/main/java/com/example/session/app/goods/GoodsController.java
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createConfirm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createFinish.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/account/createForm.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoods.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/goods/showGoodsDetail.jsp
session-tutorial-init/src/session-tutorial-init-web/src/main/webapp/WEB-INF/views/login/loginForm.jsp

[5.1.x]Session Tutorial Application is not implemented for tiles #248

---

secure-login-demo/src/secure-login-web/src/main/java/com/example/securelogin/app/account/AccountController.java
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/view.jsp

Please review #213 #214.
cherry-pick 71021eec25680c00b6d122a70f3b3534d8933473 for #213
cherry-pick fe356f68a5596586b3fa5c91c5086e22122d359f ab571866c49f8f2e84a0d1be604c2e4fb9eba882 for #214

fix does not work to the screen to complete creation of new account for 5.4.x #213 #214

---

secure-login-demo/src/secure-login-web/src/main/java/com/example/securelogin/app/account/AccountController.java
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/view.jsp

Please review #213 #214.
cherry-pick 71021eec25680c00b6d122a70f3b3534d8933473 for #213
cherry-pick fe356f68a5596586b3fa5c91c5086e22122d359f ab571866c49f8f2e84a0d1be604c2e4fb9eba882 for #214

fix does not work to the screen to complete creation of new account for 5.3.x #213 #214

---

secure-login-demo/src/secure-login-web/src/main/java/com/example/securelogin/app/account/AccountController.java
secure-login-demo/src/secure-login-web/src/main/webapp/WEB-INF/views/account/view.jsp

Please review #213 #214.
cherry-pick 71021eec25680c00b6d122a70f3b3534d8933473 for #213
cherry-pick fe356f68a5596586b3fa5c91c5086e22122d359f ab571866c49f8f2e84a0d1be604c2e4fb9eba882 for #214

fix does not work to the screen to complete creation of new account for 5.2.x #213 #214

---

.travis.yml
common/scripts/convert-common-test.sh
common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FirefoxDriverPrepare.java
common/src/test/java/org/terasoluna/gfw/tutorial/selenium/FunctionTestSupport.java
common/src/test/java/org/terasoluna/gfw/tutorial/selenium/WaitWebDriverEventListener.java
common/src/test/java/org/terasoluna/gfw/tutorial/selenium/WebDriverCreator.java
common/src/test/java/org/terasoluna/gfw/tutorial/selenium/WebDriverEventListenerAdapter.java
common/src/test/resources/META-INF/spring/selenium.properties
common/src/test/resources/META-INF/spring/seleniumContext.xml
secure-login-demo/scripts/convert-secure-login-test.sh
secure-login-demo/src/secure-login-domain/src/main/resources/META-INF/spring/secure-login-security.properties
session-tutorial-complete/src/session-tutorial-complete-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java
session-tutorial-init/src/session-tutorial-init-selenium/src/test/java/com/example/session/selenium/session/SessionTutorialTest.java

Update from Selenium 2 to Selenium 3 #313

---

ISSUE_TEMPLATE.md

Please review #322.
- Delete `Final Solution` 
- Add version template into `Fix Version/s`
- Change markdown syntax for listing

update issue template #322
